# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, bcmath, json, curl, zip
          coverage: none
          tools: composer

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress --with-all-dependencies

      - name: Run static analysis
        run: composer phpstan

      - name: Run code style checks
        run: composer pint -- --test

      - name: Run tests
        run: vendor/bin/phpunit